version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-choripy_demo}
    ports: ["5432:5432"]
    volumes: ["db_data:/var/lib/postgresql/data"]
  adminer:
    image: adminer
    restart: unless-stopped
    depends_on: [db]
    ports: ["8080:8080"]

volumes:
  db_data:
